### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by weijia-cheng** [javamanatee/frederik-pohl_short-fiction#1]
# Lint

- [x] Upgrade the toolset and copy in the new `core.css`.

# Semantics

- [x] In `the-knights-of-arthur.xhtml`, you have several instances of all-caps, which is a problem with accessibility. These need to be changed to sentence case (or at least an approximation of it) inside `<b>`s. You can use `text-transform: uppercase` in CSS to create the all-caps visual effect.
- [x] Instances of `<span xml:lang="und">` should be changed to `<i xml:lang="und">` per [8.2.9.7](https://standardebooks.org/manual/1.7.2/8-typography#8.2.9.7).
- [x] `the-tunnel-under-the-world.xhtml`: The “Feckle Freezers” chant should have `z3998:verse` semantics and use our verse formatting.
- [x] I think the GI in “Professional-GI” is supposed to be an initialism?
- [x] You will need to update your `<hgroup>`s so that the subtitle uses a `<p>`. Run `se build --check-only .` to see where to make the changes.

# Typography

- [x] Follow [8.8.8.3](https://standardebooks.org/manual/1.7.2/8-typography#8.8.8.3) for the “C:P” ratio. I’d also take away the `<abbr>` because it’s a mathematical/logical expression, not an abbreviation.

# Spelling

- [x] You should standardize on one spelling of “matériel” (probably the one with the accent since it's the first in Merriam-Webster).
- [x] Revert the modernization of `deep-freeze` to `deepfreeze`; it’s not an actual word (and I’ve filed a PR against the tools to fix that).
- [x] Initialisms that should have periods per [8.10.2](https://standardebooks.org/manual/1.7.2/8-typography#8.10.2), unless they are exceptions per [8.10.9.2](https://standardebooks.org/manual/1.7.2/8-typography#8.10.2).

# CSS

- [x] Why is the `blockquote p span` rule needed? Why not just use an `<i>`?

# Metadata

- [x] Pohl needs `<meta property="se:name.person.full-name" refines="#author">`.

# Commit History

- [x] cdccf025e1a320800468ba9ab3670ea91b26ca1c: Strictly speaking, reverting modernization changes (or reverting any other editorial commit) is not an editorial commit itself, so we should rebase out the reverts into their own commit.

**Comment by weijia-cheng** [comment]
- [x] For the `C∶P` ratio, you need a space on each side of the ratio character.
